### ISSUE TITLE
Missing migrations for SubscriptionItem

### ISSUE THREAD

**Issue by SlyDave** [jurihub/cashier-multiplan#4]
Hi,

Your work on multiplan support looks good, and could very much solve a problem of mine (once I update it to support Laravel 5.8 and Cashier 10) - but there appears to be missing files from the repo?

There is no migration for SubscriptionItem?

Thanks for your time.

**Comment by eckelarsson** [comment]
You can find the schema in the Tests for now :)

```
$this->schema()->create('subscription_items', function ($table) {
            $table->increments('id');
            $table->integer('subscription_id');
            $table->string('stripe_id');
            $table->string('stripe_plan');
            $table->integer('quantity');
            $table->timestamps();
        });
```

https://github.com/jurihub/cashier-multiplan/blob/master/tests/CashierTest.php

**Comment by SlyDave** [comment]
Thanks!
